[package]
name = "policy-evaluator"
version = "0.7.0"
authors = [
  "Flavio Castelli <fcastelli@suse.com>",
  "Rafael Fernández López <rfernandezlopez@suse.com>"
]
edition = "2021"

[workspace]
members = [
  "crates/burrego"
]

[dependencies]
anyhow = "1.0"
base64 = "0.21"
burrego = { path = "crates/burrego" }
cached = "0.42"
dns-lookup = "1.0"
json-patch = "0.3"
kube = { version = "0.80.0", default-features = false, features = ["client", "rustls-tls"] }
k8s-openapi = { version = "0.17.0", default-features = false }
#kubewarden-policy-sdk = "0.8.7"
kubewarden-policy-sdk = { git = "https://github.com/kubewarden/policy-sdk-rust", branch = "context-aware" }
itertools = "0.10"
lazy_static = "1.4"
policy-fetcher = { git = "https://github.com/kubewarden/policy-fetcher", tag = "v0.7.18" }
serde_json = "1.0"
serde_yaml = "0.9"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10"
tokio = { version = "^1", features = ["rt", "rt-multi-thread"] }
tracing = "0.1"
tracing-futures = "0.2"
url = { version = "2.2", features = ["serde"] }
validator = { version = "0.16", features = ["derive"] }
wasmparser = "0.102"
wapc = "1.0.0"
wasmtime-provider = { version = "1.4.1", features = ["cache"] }
picky = { version = "7.0.0-rc.4", default-features = false, features = [ "x509", "ec", "chrono_conversion" ] }
chrono = "0.4.23"
time = { version = "0.3.20", features = ["serde-human-readable"] }
semver = { version = "1.0.16", features = ["serde"] }
email_address = {version = "0.2.4", features = ["serde"] }
mail-parser= {version = "0.8.2", features = ["serde"] }
thiserror = "1.0"

[dev-dependencies]
assert-json-diff = "2.0"
k8s-openapi = { version = "0.17.0", default-features = false, features = ["v1_24"] }
